def config = readYaml text: "${env.PIPELINE_CONFIG}"
pipeline {
  agent {
    label "${config.agent_label}"
  }
  stages {
    stage("run run ANYTHING") {
      steps {
        echo "What to run: ${config.run_me}"
        sh "${config.run_me}"
        sh "docker run --rm ${config.docker_container} ${config.script_to_run}"
      }
    }
  }
}
