def config = readYaml text: "${env.PIPELINE_CONFIG}"
pipeline {
  agent {
    label "${config.agent_label}"
  }
  stages {
    stage("run run ANYTHING") {
      steps {
        echo "What to run: ${config.run_me}"
        sh "docker run --rm -v `pwd`:/tmp/project ${config.docker_container} /bin/sh -c \"cd /tmp/project && ${config.run_me}\""
      }
    }
  }
}
