def config = readYaml text: "${env.PIPELINE_CONFIG}"

pipeline {
  agent any
  stages {
    stage('CI Build and push snapshot') {
      when {
        branch 'PR-*'
      }
      steps {
        echo "Your config: ${config}"
        sh "docker run --rm -v `pwd`:/tmp/project python:3.7-stretch /bin/sh -c \"cd /tmp/project && ${config.script_to_run}\""
      }
    }
    stage('Build Release') {
      when {
        branch 'master'
      }
      steps {
        echo "Your config: ${config}"
        sh "docker run --rm -v `pwd`:/tmp/project python:3.7-stretch /bin/sh -c \"cd /tmp/project && ${config.script_to_run}\""
        echo "RELEASED!"
      }
    }
  }
}
