def config = readYaml text: "${env.PIPELINE_CONFIG}"

pipeline {
  agent any
  stages {
    stage('CI Build and push snapshot') {
      when {
        branch 'PR-*'
      }
      steps {
        echo "Your config: ${config}"
        sh "docker run --rm python:3.7-stretch ${config.script_to_run}"
      }
    }
    stage('Build Release') {
      when {
        branch 'master'
      }
      steps {
        echo "Your config: ${config}"
        sh "docker run --rm python:3.7-stretch ${config.script_to_run}"
        echo "RELEASED!"
      }
    }
  }
}
